# Generated by Django 4.0 on 2022-01-07 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_movies_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stripe_customer_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
