# Generated by Django 4.0 on 2022-01-05 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermembership',
            name='membership',
        ),
        migrations.RemoveField(
            model_name='usermembership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='user_membership',
        ),
    ]
