# Generated by Django 4.0 on 2022-01-05 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
        ('memberships', '0003_remove_usermembership_membership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='profile',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='users.profile'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserMembership',
        ),
    ]
